### ISSUE TITLE
Restrict metabox to be displayed on a specific page template

### ISSUE THREAD

**Issue by cristianobaptista** [ponticlaro/bebop-cms#1]
Something like:

``` php
$metabox->restrictToTemplates([
    'tpl-home.php',
    'tpl-contact-us.php'
]);
```

**Comment by jrconway3** [comment]
This could be interesting, but the main problem I see with it is that this wouldn't take effect until after you save the page. Unless we just display them by default and keep them hidden, and when toggling the template it automatically shows the metaboxes we need.

In our case we'd know what we needed to do, but what if the clients wanted to add a new page with that page template?

**Comment by cristianobaptista** [comment]
Yeah, I'm aware that the metabox will be only available after saving an
entry with a matching template selected.

We could probably handle this by adding a WordPress notification at the top
with information about extra content available on the selected template (or
a link to that information, within the same page or not) or/and have a
clearly visible metabox (or subsection within the template selector
metabox) with info about the extra content available. Note that the
notification at the top would inly be displayed after saving the entry.

Regarding using javascript to toggle metaboxes as we change the template
might work for the user if we have something that tells them about the
template details whenever they change templates on the dropdown, but for
each hidden metabox it would run through all meta fields to try to save
them on each entry and this might slow down things a lot after adding a ton
of conditional metaboxes. We might be able to solve this by hooking into
the save post meta hook and somehow remove the fields we do not need to
handle.

**Comment by jrconway3** [comment]
"but for each hidden metabox it would run through all meta fields to try to
save them on each entry and this might slow down things a lot after adding
a ton of conditional metaboxes"

Yeah, this is something I was concerned about as well.
